Unit test
frozen599/s3-assignment pull request #4
Opened 2023-01-10 06:57 UTC by frozen599

2023-01-11 04:32 UTC, nhan1603 requested changes
Please perform similar checks for all the commented issues.

2023-01-11 04:32 UTC, nhan1603 commented on api/cmd/friends/main.go
> +	fmt.Println(cfg)
remove this  print command as the configuration will be printed on the log

2023-01-11 04:32 UTC, nhan1603 commented on api/internal/controller/subscriber.go
> +	err = sc.relaRepo.CreateRelationship(blockingRelationShip)
can we return the result from repository immediately ?

2023-01-11 04:32 UTC, nhan1603 commented on api/internal/handler/subscriber_handler_test.go
> +	//defer dbInstance.Exec(string(deleteData))
Commented LOCs can be removed.

2023-01-11 04:32 UTC, nhan1603 commented on api/internal/controller/test_data/delete_data.sql
> +
Remove empty line

2023-01-11 04:32 UTC, nhan1603 commented on api/internal/pkg/response.go
>  		log.Fatal(err)
Why should we stop the program when the writer cannot serialize the response ?

2023-01-11 10:17 UTC, nhan1603 requested changes

2023-01-11 10:17 UTC, nhan1603 commented on api/internal/pkg/response.go
> +		fmt.Println(err)
please return here and process the response writer to write an error message for user to understand

2023-01-16 03:58 UTC, nhan1603 approved these changes
LGTM

2023-01-16 03:58 UTC, merged

2023-01-16 04:01 UTC, frozen599 commented on api/cmd/friends/main.go
> +	fmt.Println(cfg)
resolved in 4159eeb1fb0894dc0652209c0914bc5d301eb413